apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: ${IMAGE_TAG}
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /
            port: 80
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
  - name: http
    port: 80

